spring:
  application:
    name: back
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api/api-docs

logging:
  level:
    root: info
    org.springframework: warn
    org.springframework.security: debug
    com.cocoa.backend: debug


